apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../rollouts
images:
  - name: sentinel-api
    newName: ghcr.io/amrufai/sentinel-api
    newTag: v5.0.0
patches:
  - path: service-lb.yaml
  - target:
      kind: Rollout
      name: sentinel-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
