apiVersion: v1
kind: Service
metadata:
  name: sentinel-api
  namespace: sentinel
  labels:
    app: sentinel-api
spec:
  selector:
    app: sentinel-api
  ports:
    - name: http
      port: 80
      targetPort: 3000