apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentinel-api
  namespace: sentinel
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: sentinel-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s