apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-runasnonroot
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - sentinel
      validate:
        message: "Containers must run as non-root (set runAsNonRoot: true)."
        pattern:
          spec:
            =(securityContext):
              runAsNonRoot: true