apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentinel-api-secret-aws
  namespace: sentinel
spec:
  secretStoreRef:
    name: aws-real-store
    kind: SecretStore
  target:
    name: sentinel-api-secret-aws
  data:
    - secretKey: apiKey
      remoteRef:
        key: sentinel/api-key
        property: apiKey