apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-real-store
  namespace: sentinel
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-real-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-real-creds
            key: secret-key
            