apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-store
  namespace: sentinel
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-creds
            key: access-key
          secretAccessKeySecretRef:
            name: localstack-creds
            key: secret-key