name: Terraform
on:
  push:
    paths: ['infra/**', 'policies/terraform/**']
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  TF_VAR_my_ip: ${{ secrets.MY_IP }}

jobs:
  plan-and-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -out=tfplan
      - run: terraform show -json tfplan > plan.json
      - name: Install conftest
        run: |
          CONFT_VER=$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
          wget -qO conftest.tar.gz "https://github.com/open-policy-agent/conftest/releases/download/v${CONFT_VER}/conftest_${CONFT_VER}_Linux_x86_64.tar.gz"
          tar xzf conftest.tar.gz conftest
      - name: Policy gate (Conftest vs plan JSON)
        working-directory: .
        run: ./conftest test infra/plan.json --policy policies/terraform --no-color

  apply:
    needs: plan-and-check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production        # <-- pauses here for your manual approval
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve